version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z

  chainlitapp:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      HOST: 0.0.0.0
      LISTEN_PORT: 8000
    depends_on:
      - qdrant